# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8081}
    error.whitelabel.enabled: false

# EUREKA
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:


# LOGGING
#logging.level.org.springframework.security: DEBUG
---

spring:
  profiles: docker

# EUREKA
eureka:
  instance:
    hostname: discovery-service
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
---


spring:
  profiles: standalone

# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
