# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:50002}
spring:
    aop:
        proxyTargetClass: true
# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
# ZULL
zuul:
  routes:
    nothing-service:
      sensitiveHeaders:
      path: /nothing/**
      stripPrefix: false
 
#SECURITY
security:
  basic:
    enabled: false
 
# LOGGING
logging.level.org.springframework.security: DEBUG

---

spring:
  profiles: docker

# EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/
---

spring:
  profiles: dev

# EUREKA
eureka:
  instance:
    hostname: discovery-service
    port: 50001
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
---
